CREATE TABLE BPM_PROCESS_CONFIG(
  ID VARCHAR(32) NOT NULL PRIMARY KEY ,
  PROCESS_DEF_KEY VARCHAR(50) NOT NULL ,
  TASK_DEF_KEY VARCHAR(50) NOT NULL ,
  TASK_DEF_TYPE CHAR(1) NOT NULL ,
  TASK_CONFIG VARCHAR(200)
)

